version: "3.9"

services:
  rust-server-1:
    build: .
    ports:
      - "8001:8001"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-1:8001
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007

  rust-server-2:
    build: .
    ports:
      - "8002:8002"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-2:8002
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007

  rust-server-3:
    build: .
    ports:
      - "8003:8003"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-3:8003
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007

  rust-server-4:
    build: .
    ports:
      - "8004:8004"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-4:8004
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007

  rust-server-5:
    build: .
    ports:
      - "8005:8005"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-5:8005
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007

  rust-server-6:
    build: .
    ports:
      - "8006:8006"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-6:8006
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007

  rust-server-7:
    build: .
    ports:
      - "8007:8007"
    environment:
      - RUST_LOG=info
      - CURRENT_NODE_IP=rust-server-7:8007
      - ALL_NODE_IPS=rust-server-1:8001,rust-server-2:8002,rust-server-3:8003,rust-server-4:8004,rust-server-5:8005,rust-server-6:8006,rust-server-7:8007
